<?php

namespace App\Tests\Unit;


use App\Service\GoogleClient\GoogleClient;
use PHPUnit\Framework\TestCase;

class GoogleClientTest extends TestCase
{

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

    }

    public function updates_values_successfully_to_sheets(){



    }

}